spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2857944093/config-repo
          username: 2857944093
          password: qq2459899769
          basedir: E:/czk/SpringCloud/config/basedir
  rabbitmq:
    host: 106.15.180.75
    port: 5672
    Virtual Host: my_vhost
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
