eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka2:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
