eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/,http://localhost:8762/eureka/,http://localhost:8761/eureka/
  #自定义连接
  #instance:
    #hostname: clientName
spring:
  application:
    name: client
